### ISSUE TITLE
Support for traverse-with-class version 1.x?

### ISSUE THREAD

**Issue by peti** [faylang/fay#447]
Is there any chance to release an updated version of this package to Hackage which supports recent versions of `traverse-with-class`? This would allow us to keep building and distributing this package for openSUSE. Currently, the build fails after we updated our package set to LTS-9.

**Comment by bergmark** [comment]
Sorry for the delay!

I don't have much time to work on fay so I'm not likely to get around to this myself, but I assume it is possible and I'd welcome the contribution! Another option would be to drop the old inlined version of haskell-names and use the latest version of that. But it looks like that package would have to be updated for traverse-with-class as well. haskell-names is only inlined into fay since I wanted to keep fay in stackage and didn't have time for that upgrade when it happened...

**Comment by henrylaxen** [comment]
Hey Adam, I think you can close this since you merged my pull request back in Jan.

**Comment by bergmark** [comment]
Thanks!
