### ISSUE TITLE
getRuntime and getConfigRuntime disappeared

### ISSUE THREAD

**Issue by maxigit** [faylang/fay#451]
getRuntime has disappeared as well as getConfigRuntime. This break yesod-fay module.

**Comment by bergmark** [comment]
Thanks for the report,

I forgot that this became part of the 0.24.0.0 release, dropping `getRuntime` does make some sense since you now get different results depending on if you are generating javascript or typescript.

Is it possible to update yesod-fay to use  the new `readConfigRuntime :: Config -> IO String`? It should be a drop in replacement for `getConfigRuntime`

Either way, I t would be ok by me to add these functions again to remain backwards-compatible, they could be marked as deprecated. Would you be interested in sending a PR?

In the meantime you should be able to keep using yesod-fay with `fay < 0.24`

**Comment by maxigit** [comment]
I've tried but, replacing the call to getRunTime in yesod-fay by something
or putting back getRunTime = this something in Fay should be equivalent.
Unfortunately I didn't manage to do so.
Also, fay doesn't work with the last version of GHC. I'm hoping to move the
new version
when this is fixed, so staying with fay < 0.24 is not ideal.

**Comment by swamp-agr** [comment]
Hi @maxigit, I could suggest to wait for fpco/yesod-fay#21 resolution.

**Comment by maxigit** [comment]
Brilliant. I didn't see it and it should indeed solve my problem.

**Comment by swamp-agr** [comment]
@maxigit, 

Actually, it was created a few days ago and merged some hours ago.
As far as I see the changes had already been applied and present on Hackage as `yesod-fay-0.9.0`.  

So, if it fixes your problem then you could close the issue!

Thanks,
Andrey

**Comment by maxigit** [comment]
I've tried it yet, but I'll close the issue and reopen it if it doesn't solve the problem.

**Comment by swamp-agr** [comment]
Hi @maxigit, 

Thanks! I have a project 

- Yesod+Fay under the hood,
- with OSX as host system, 
- Ubuntu as target system,
- 2 different `stack` configs (with and without docker).

And a couple of notes how to run `fay` across it.
One trick helped me especially a lot when I tried to add new Fay file in the project.

For linux projects I do:

```
export GHC_PACKAGE_PATH=$(stack path --ghc-package-path)
```

For osx project: 

```
unset GHC_PACKAGE_PATH
```

It caused by: 

- `Fay.Compiler.Packages` uses `ghc_pkg` from `ghc-paths` package. 
- It refers to global package database. 
- In case of stack: somewhere inside `~/.stack/.../*linux*/...`. 
- But for some reason `fay` is not there but it located in `~/my/project/.stack-work/...`. 

So, this trick looks like workaround. Actually, it is workaround. I am thinking about how to mitigate it with proper combination of `cabal`/`ghc`/`stack` options.
